"""Ajout des commentaires sur les offres

Revision ID: 1a0acbeb6503
Revises: 99d704c4e5e0
Create Date: 2025-08-17 03:00:05.491093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0acbeb6503'
down_revision = '99d704c4e5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentaire_offre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.Column('reponses', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['offre_id'], ['offre.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentaire_offre')
    # ### end Alembic commands ###
