"""empty message

Revision ID: 7742ad40fdab
Revises: fef542463f41
Create Date: 2025-08-22 16:52:37.817490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7742ad40fdab'
down_revision = 'fef542463f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secteur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secteur', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
