"""Ajout mot_de_passe à Partenaire

Revision ID: 99208d371c50
Revises: 7742ad40fdab
Create Date: 2025-08-25 16:08:53.483908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99208d371c50'
down_revision = '7742ad40fdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partenaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mot_de_passe', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partenaire', schema=None) as batch_op:
        batch_op.drop_column('mot_de_passe')

    # ### end Alembic commands ###
