"""Ajout email propre à Partenaire

Revision ID: f7bf3d579513
Revises: 99208d371c50
Create Date: 2025-08-25 17:33:58.091138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f7bf3d579513'
down_revision = '99208d371c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_partenaire')
    with op.batch_alter_table('partenaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_partenaire_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partenaire', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_partenaire_email', type_='unique')
        batch_op.drop_column('email')

    op.create_table('_alembic_tmp_partenaire',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('secteur_id', sa.INTEGER(), nullable=False),
    sa.Column('categorie_partenaire_id', sa.INTEGER(), nullable=False),
    sa.Column('localisation', sa.VARCHAR(length=150), nullable=True),
    sa.Column('ville', sa.VARCHAR(length=100), nullable=True),
    sa.Column('commune', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('contact', sa.VARCHAR(length=100), nullable=True),
    sa.Column('date_inscription', sa.DATETIME(), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=250), nullable=True),
    sa.Column('url', sa.VARCHAR(length=250), nullable=True),
    sa.Column('reseaux', sqlite.JSON(), nullable=True),
    sa.Column('note_moyenne', sa.FLOAT(), nullable=True),
    sa.Column('photos', sqlite.JSON(), nullable=True),
    sa.Column('mot_de_passe', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), server_default=sa.text("'temp@example.com'"), nullable=True),
    sa.ForeignKeyConstraint(['categorie_partenaire_id'], ['categorie_partenaire.id'], name=op.f('fk_partenaire_categorie')),
    sa.ForeignKeyConstraint(['secteur_id'], ['secteur.id'], name=op.f('fk_partenaire_secteur')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name=op.f('uq_partenaire_email'))
    )
    # ### end Alembic commands ###
